pipeline {
  agent any
  environment {
    DOCKERHUB_PASS = 'PSCKparu_22'
  }
  stages {
    stage ("Building the web app into a docker image"){
      steps {
        script {
          checkout scm
          sh 'rm -rf SWE645_Doan_HW1/src/main/webapp/*.war'
          sh 'jar -cvf studentSurvey.war -C SWE645_Doan_HW1/src/main/webapp/ .'
          sh 'echo ${BUILD_TIMESTAMP}'
          sh "sudo docker login -u cparupal -p ${DOCKERHUB_PASS}"
          def customImage = docker.build("cparupal/studentsurvey645:${BUILD_TIMESTAMP}")
        }
      }
    }

    stage("Pushing Image to Dockerhub"){
      steps{
        script{
          sh 'docker push cparupal/studentsurvey645:${BUILD_TIMESTAMP}'
        }
      }
    }

  }
}
