pipeline {
  agent any
  environment {
    DOCKERHUB_PASS = credentials('docker-pass')
  }
  stages {
    stage ("Building the web app into a docker image"){
      steps {
        script {
          checkout scm
          sh 'rm -rf SWE645_Doan_HW1/src/main/webapp/*.war'
          sh 'jar -cvf studentSurvey.war -C SWE645_Doan_HW1/src/main/webapp/ .'
          sh 'echo ${BUILD_TIMESTAMP}'
          sh "docker login -u cparupal -p $DOCKERHUB_PASS_PSW"
          sh 'pwd'
          sh "docker build -t cparupal/studentsurvey645:1.1 SWE645_Doan_HW1/src/main/webapp/"
          
        }
      }
    }

    stage("Pushing Image to Dockerhub"){
      steps{
        script{
          sh "docker push cparupal/studentsurvey645:${BUILD_TIMESTAMP}"
        }
      }
    }

  }
}
